CREATE TABLE combinations(
  id INTEGER NOT NULL,
  year VARCHAR(20) NOT NULL,
  date VARCHAR(20) NOT NULL,
  val1 INTEGER NOT NULL,
  val2 INTEGER NOT NULL,
  val3 INTEGER NOT NULL,
  val4 INTEGER NOT NULL,
  val5 INTEGER NOT NULL,
  model VARCHAR(5) NOT NULL,
  model_ranges VARCHAR(5) NOT NULL,
  PRIMARY KEY(id)
);
